improved multi-cluster support

diff --git a/bin/playground b/bin/playground
--- a/bin/playground
+++ b/bin/playground
@@ -73,7 +73,7 @@ function menu_main() {
                     "Deploy" "Deploy Services..." \
                     "Clusters" "Select Cluster Context..." \
                     "Delete" "(Danger Zone) Delete Services..." \
-                    "Kill" "(Danger Zone) Tear Down Cluster" \
+                    "Kill" "(Danger Zone) Tear Down Cluster..." \
                     "Status" "Namespaces, LoadBalancers, Deployments & DaemonSets" \
                     "Services" "Services, Addresses and Credentials" \
                     "Disk Space" "Display Disk Space" \
@@ -142,10 +142,7 @@ function menu_main() {
                 menu_delete || true
                 ;;
             "Kill")
-                if [ -f "$PGPATH/bin/.teardown.sh" ]; then
-                    clear
-                    $PGPATH/bin/.teardown.sh
-                fi
+                menu_teardown_cluster
                 ;;
             "Status")
                 if $(kubectl config current-context &>/dev/null); then
@@ -163,6 +160,9 @@ function menu_main() {
             "Services")
                 if [ -f $PGPATH/services ]; then
                     result=$(cat $PGPATH/services)
+                    display_result "Addresses & Credentials"
+                else
+                    result="No services file found"
                     display_result "Addresses & Credentials"
                 fi
                 ;;
@@ -354,24 +354,86 @@ function menu_create_cluster() {
                     result="Please adapt /etc/docker/daemon.json.\n\nSee README.md."
                     display_result
                 else
-                    echo "$PGPATH/bin/rapid-kind-down.sh" > $PGPATH/bin/.teardown.sh && chmod +x $PGPATH/bin/.teardown.sh
+                    # echo "$PGPATH/bin/rapid-kind-down.sh" > $PGPATH/bin/.teardown.sh && chmod +x $PGPATH/bin/.teardown.sh
                     $PGPATH/bin/rapid-kind.sh
                 fi
                 ;;
             "EKS") 
                 clear
-                echo "$PGPATH/bin/rapid-eks-down.sh" > $PGPATH/bin/.teardown.sh && chmod +x $PGPATH/bin/.teardown.sh
+                # echo "$PGPATH/bin/rapid-eks-down.sh" > $PGPATH/bin/.teardown.sh && chmod +x $PGPATH/bin/.teardown.sh
                 $PGPATH/bin/rapid-eks.sh
                 ;;
             "AKS")
                 clear
-                echo "$PGPATH/bin/rapid-aks-down.sh" > $PGPATH/bin/.teardown.sh && chmod +x $PGPATH/bin/.teardown.sh
+                # echo "$PGPATH/bin/rapid-aks-down.sh" > $PGPATH/bin/.teardown.sh && chmod +x $PGPATH/bin/.teardown.sh
                 $PGPATH/bin/rapid-aks.sh
                 ;;
             "GKE")
                 clear
-                echo "$PGPATH/bin/rapid-gke-down.sh" > $PGPATH/bin/.teardown.sh && chmod +x $PGPATH/bin/.teardown.sh
+                # echo "$PGPATH/bin/rapid-gke-down.sh" > $PGPATH/bin/.teardown.sh && chmod +x $PGPATH/bin/.teardown.sh
                 $PGPATH/bin/rapid-gke.sh
+                ;;
+            *) 
+                ;;
+        esac
+    done
+}
+
+function menu_teardown_cluster() {
+
+    # exec 3>&1
+    items=("Kind" "Local Cluster" \
+           "EKS" "Elastic Kubernetes Cluster" \
+           "AKS" "Azure Kubernetes Cluster" \
+           "GKE" "Google Kubernetes Engine")
+    TITLE="Teardown a Cluster"
+    check_k8s
+    BACKTITLE="Playground: ${CLUSTER}"
+    while choice=$(dialog --title "${TITLE}" \
+                    --backtitle "${BACKTITLE}" \
+                    --cancel-label "Back" \
+                    --separate-widget "Widget" \
+                    --menu "Please select" ${HEIGHT} ${WIDTH} 4 "${items[@]}" \
+                    2>&1 1>&3)
+    do
+        exit_status=$?
+        case $exit_status in
+            $DIALOG_CANCEL)
+            clear
+            echo "Going back."
+            break
+            ;;
+            $DIALOG_ESC)
+            clear
+            echo "Program aborted." >&2
+            exec 3>&-
+            exit 1
+            ;;
+        esac
+        case $choice in
+            "Kind")
+                if [ -f "$PGPATH/bin/rapid-kind-down.sh" ]; then
+                    clear
+                    $PGPATH/bin/rapid-kind-down.sh
+                fi
+                ;;
+            "EKS") 
+                if [ -f "$PGPATH/bin/rapid-eks-down.sh" ]; then
+                    clear
+                    $PGPATH/bin/rapid-eks-down.sh
+                fi
+                ;;
+            "AKS")
+                if [ -f "$PGPATH/bin/rapid-aks-down.sh" ]; then
+                    clear
+                    $PGPATH/bin/rapid-aks-down.sh
+                fi
+                ;;
+            "GKE")
+                if [ -f "$PGPATH/bin/rapid-gke-down.sh" ]; then
+                    clear
+                    $PGPATH/bin/rapid-gke-down.sh
+                fi
                 ;;
             *) 
                 ;;
@@ -385,12 +447,14 @@ function menu_select_context() {
 
     items=($(kubectl config get-contexts -o name | \
         awk -v current=$(kubectl config current-context) '
-            BEGIN{i=0}{
+            {
                 onoff="off"
                 if (current == $0) onoff="on"
                 printf("%s %s %s\n", $0, onoff, onoff)
             }
         '))
+
+    cp $PGPATH/services $PGPATH/services-$(kubectl config current-context)
 
     TITLE="Select a Context"
     check_k8s
@@ -417,6 +481,11 @@ function menu_select_context() {
             ;;
         esac
         kubectl config use-context $choice
+        local currentcontext=$(kubectl config current-context)
+        if [ ! -f $PGPATH/services-$currentcontext ]; then
+            touch $PGPATH/services-$currentcontext
+        fi
+        cp $PGPATH/services-$currentcontext $PGPATH/services
         break
     done
 }
